#!/usr/bin/env python3
"""Port the two interactive tools into the Next.js app as ES modules.

planner.js and calculator.js are data-driven and already match the mod's own
Java (skilltree data is generated from SkillTreeRegistry; the calculator
hardcodes the real Qi curve). Rewriting that logic in React would risk silent
numeric drift for no gain, so the logic is kept verbatim and only its wrapper
changes: the IIFE becomes a module with an exported init(), the globals become
an import and a parameter.
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
WEB = ROOT / "web"
OUT_TOOLS = WEB / "lib" / "tools"
OUT_DATA = WEB / "lib" / "data"

HEADER = """/* Ported from the static site's assets/js/{name} by tools/port_tools.py.

   The logic is deliberately unchanged — it matches the mod's own Java — and
   only the wrapper differs: an ES module exporting init(lang) in place of an
   IIFE that read globals and waited for DOMContentLoaded. React calls init()
   from an effect once the markup it binds to is mounted.
*/
"""


def extract_skilltree() -> int:
    src = (ROOT / "data" / "skilltree.js").read_text(encoding="utf-8")
    match = re.search(r"window\.SKILL_TREE\s*=\s*(\{.*\});?\s*$", src, re.S)
    if not match:
        sys.exit("could not find window.SKILL_TREE assignment")
    data = json.loads(match.group(1))
    OUT_DATA.mkdir(parents=True, exist_ok=True)
    out = OUT_DATA / "skilltree.json"
    out.write_text(json.dumps(data, ensure_ascii=False, separators=(",", ":")),
                   encoding="utf-8")
    # Sanity checks mirroring make_skilltree_data.py's own assertions.
    assert len(data["nodes"]) == 117, f"expected 117 nodes, got {len(data['nodes'])}"
    assert len(data["branches"]) == 9, "expected 9 branches"
    return out.stat().st_size


def port_planner() -> int:
    src = (ROOT / "assets" / "js" / "planner.js").read_text(encoding="utf-8")

    # Drop the leading banner comment; the module gets its own.
    src = re.sub(r"^/\*.*?\*/\s*", "", src, count=1, flags=re.S)

    # IIFE -> module.
    src = re.sub(r'^\(function \(\) \{\s*"use strict";\s*', "", src, count=1)
    src = re.sub(r"\n\s*if \(document\.readyState === \"loading\"\).*?\n\}\)\(\);\s*$",
                 "\n", src, count=1, flags=re.S)

    # Globals -> import + parameter.
    src = re.sub(
        r'var DATA = window\.SKILL_TREE;\s*\n\s*if \(!DATA\) \{[^\n]*\n',
        "", src, count=1)
    src = re.sub(
        r'var LANG = \(document\.documentElement\.lang[^\n]*\n',
        "", src, count=1)

    body = HEADER.format(name="planner.js") + (
        'import DATA from "../data/skilltree.json";\n\n'
        "export function init(LANG) {\n"
        + indent(src.strip())
        + "\n\n  boot();\n}\n"
    )
    OUT_TOOLS.mkdir(parents=True, exist_ok=True)
    out = OUT_TOOLS / "planner.js"
    out.write_text(body, encoding="utf-8")
    return out.stat().st_size


def port_calculator() -> int:
    src = (ROOT / "assets" / "js" / "calculator.js").read_text(encoding="utf-8")
    src = re.sub(r"^/\*.*?\*/\s*", "", src, count=1, flags=re.S)
    src = re.sub(r'^\(function \(\) \{\s*"use strict";\s*', "", src, count=1)
    src = re.sub(r"\n\s*if \(document\.readyState === \"loading\"\).*?\n\}\)\(\);\s*$",
                 "\n", src, count=1, flags=re.S)
    src = re.sub(r'var LANG = \(document\.documentElement\.lang[^\n]*\n', "", src, count=1)

    body = HEADER.format(name="calculator.js") + (
        "export function init(LANG) {\n"
        + indent(src.strip())
        + "\n\n  boot();\n}\n"
    )
    OUT_TOOLS.mkdir(parents=True, exist_ok=True)
    out = OUT_TOOLS / "calculator.js"
    out.write_text(body, encoding="utf-8")
    return out.stat().st_size


def indent(text: str, pad: str = "  ") -> str:
    return "\n".join(pad + line if line.strip() else line for line in text.split("\n"))


# ---------------------------------------------------------------------------
# Tool page shells
# ---------------------------------------------------------------------------
SHELL_HEADER = """/* GENERATED by tools/port_tools.py — do not edit by hand.

   The two tool pages are form markup whose ids and data-* attributes are a
   contract with planner.js / calculator.js. Hand-transcribing ~15 KB of inputs
   into JSX would risk a silent typo breaking a binding, so the markup is
   lifted verbatim from the pages that already work and rendered as-is. It is
   still server-rendered — this is a build-time constant, not a fetch.
*/
"""


def extract_shell(path: pathlib.Path, lang: str) -> str:
    """Inner HTML of <main class="content">, with paths made root-absolute."""
    raw = path.read_text(encoding="utf-8")
    match = re.search(r'<main class="content"[^>]*>(.*?)</main>', raw, re.S)
    if not match:
        sys.exit(f"{path}: no <main class=\"content\">")
    body = match.group(1)

    prefix = "/zh/" if lang == "zh" else "/"
    # zh pages sit one level deeper, so they reach English with ../../.
    body = body.replace('href="../../', 'href="/')
    body = body.replace('src="../../', 'src="/')
    body = re.sub(r'(href|src)="\.\./', lambda m: f'{m.group(1)}="{prefix}', body)
    return body.strip()


HERO_HEADER = """/* GENERATED by tools/port_tools.py — do not edit by hand.

   The home page hero: a hand-drawn inline SVG mountain scene, the seal, the
   title block and the call-to-action buttons. Lifted verbatim rather than
   transcribed into JSX — it is decorative vector art where a mistyped path
   coordinate would be invisible in review and obvious on the page.

   The <canvas class="hero-motes"> stays in this markup; HeroMotes finds it in
   the DOM and drives it, which avoids wrapping the hero's absolutely
   positioned children in an element that would disturb the layout.
*/
"""


def extract_hero(path: pathlib.Path, lang: str) -> str:
    raw = path.read_text(encoding="utf-8")
    # Inner HTML only: the component renders the <section class="hero"> itself,
    # so nothing wraps the hero's absolutely positioned children.
    match = re.search(r'<section class="hero">(.*?)</section>', raw, re.S)
    if not match:
        sys.exit(f"{path}: no <section class=\"hero\">")
    hero = match.group(1)

    # Assets are shared and live at the root; page links belong to this
    # language's tree (the zh hero links "getting-started/" relative to /zh/).
    hero = hero.replace('src="../assets/', 'src="/assets/')
    hero = hero.replace('src="assets/', 'src="/assets/')
    prefix = "/zh/" if lang == "zh" else "/"
    hero = re.sub(r'href="(?!/|https?:|#)([^"]+)"', lambda m: f'href="{prefix}{m.group(1)}"', hero)
    return hero.strip()


def port_home() -> int:
    pairs = [
        ("heroEn", ROOT / "index.html", "en"),
        ("heroZh", ROOT / "zh" / "index.html", "zh"),
    ]
    parts = [HERO_HEADER]
    for name, path, lang in pairs:
        if not path.exists():
            sys.exit(f"missing home page: {path}")
        html = extract_hero(path, lang)
        html = html.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
        parts.append(f"export const {name} = `{html}`;\n")

    out_dir = WEB / "lib" / "home"
    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / "hero.ts"
    out.write_text("\n".join(parts), encoding="utf-8")
    return out.stat().st_size


def port_shells() -> int:
    pairs = [
        ("plannerEn", ROOT / "planner" / "index.html", "en"),
        ("plannerZh", ROOT / "zh" / "planner" / "index.html", "zh"),
        ("calculatorEn", ROOT / "calculator" / "index.html", "en"),
        ("calculatorZh", ROOT / "zh" / "calculator" / "index.html", "zh"),
    ]
    parts = [SHELL_HEADER]
    for name, path, lang in pairs:
        if not path.exists():
            sys.exit(f"missing tool page: {path}")
        html = extract_shell(path, lang)
        # A backtick or ${ inside the markup would break the template literal.
        html = html.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
        parts.append(f"export const {name} = `{html}`;\n")

    OUT_TOOLS.mkdir(parents=True, exist_ok=True)
    out = OUT_TOOLS / "shells.ts"
    out.write_text("\n".join(parts), encoding="utf-8")
    return out.stat().st_size


def main() -> None:
    print(f"  skilltree.json   {extract_skilltree():>7,} bytes")
    print(f"  planner.js       {port_planner():>7,} bytes")
    print(f"  calculator.js    {port_calculator():>7,} bytes")
    print(f"  shells.ts        {port_shells():>7,} bytes")
    print(f"  hero.ts          {port_home():>7,} bytes")

    # The boot functions must have survived the rewrap.
    for name in ("planner.js", "calculator.js"):
        text = (OUT_TOOLS / name).read_text(encoding="utf-8")
        if "function boot(" not in text:
            sys.exit(f"{name}: boot() disappeared during the rewrap")
        if "window.SKILL_TREE" in text or "document.readyState" in text:
            sys.exit(f"{name}: a global survived the rewrap")
    print("\nboot() present and globals removed in both modules")


if __name__ == "__main__":
    main()
