#!/usr/bin/env python3
"""Stamp Open Graph, Twitter-card and canonical tags into every page.

Social crawlers (Discord, X, Slack, Facebook) do NOT run JavaScript, so these
tags have to be real HTML in each file — they cannot be injected by site.js like
the rest of the chrome. og:url and og:image must also be absolute, which is why
the site's public address is hard-coded here.

    >>> CHANGE SITE_URL BELOW IF YOU PUBLISH ON A DIFFERENT DOMAIN <<<
    then re-run:  python tools/stamp_meta.py

Re-running is safe: the block is delimited and replaced wholesale, never
duplicated. Run it after tools/convert_docs.py, which rewrites generated pages.
"""
from __future__ import annotations

import html
import pathlib
import re
import sys

# --------------------------------------------------------------------------
SITE_URL = "https://cultivation.mermaids.dev"      # no trailing slash
SITE_NAME = "Cultivation Wiki"
CARD = "/assets/img/social-card.png"
CARD_W, CARD_H = 1200, 630
# --------------------------------------------------------------------------

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKIP_DIRS = {".git", "assets", "tools", "data", "node_modules"}

BEGIN = "<!-- social:begin (generated by tools/stamp_meta.py) -->"
END = "<!-- social:end -->"


def page_url(rel: str) -> str:
    if rel == "index.html":
        return SITE_URL + "/"
    if rel.endswith("/index.html"):
        return f"{SITE_URL}/{rel[:-len('index.html')]}"
    return f"{SITE_URL}/{rel}"


def tag(name: str, content: str, prop: bool = True) -> str:
    attr = "property" if prop else "name"
    return f'<meta {attr}="{name}" content="{html.escape(content, quote=True)}">'


def block(title: str, desc: str, url: str, noindex: bool) -> str:
    lines = [BEGIN, f'<link rel="canonical" href="{html.escape(url, quote=True)}">']
    if noindex:
        lines.append('<meta name="robots" content="noindex">')
    lines += [
        tag("og:site_name", SITE_NAME),
        tag("og:type", "website"),
        tag("og:url", url),
        tag("og:title", title),
        tag("og:description", desc),
        tag("og:image", SITE_URL + CARD),
        tag("og:image:width", str(CARD_W)),
        tag("og:image:height", str(CARD_H)),
        tag("og:image:alt", "Cultivation — a Xianxia progression mod for Hytale"),
        tag("twitter:card", "summary_large_image", prop=False),
        tag("twitter:title", title, prop=False),
        tag("twitter:description", desc, prop=False),
        tag("twitter:image", SITE_URL + CARD, prop=False),
        END,
    ]
    return "\n".join(lines)


def main() -> None:
    pages = sorted(
        p for p in ROOT.rglob("*.html")
        if not any(part in SKIP_DIRS for part in p.relative_to(ROOT).parts)
    )
    if not pages:
        sys.exit("no pages found")

    for path in pages:
        rel = path.relative_to(ROOT).as_posix()
        s = path.read_text(encoding="utf-8")

        # Both sources are already HTML-escaped in the page; unescape first so
        # that re-escaping for the meta attribute cannot double up (&amp;amp;).
        m = re.search(r"<title>(.*?)</title>", s, re.S)
        title = html.unescape(re.sub(r"\s+", " ", m.group(1)).strip()) if m else SITE_NAME
        m = re.search(r'<meta name="description" content="([^"]*)"', s)
        desc = html.unescape(m.group(1)) if m else ""

        # 404 already carries its own noindex; don't advertise it socially either.
        noindex = path.name == "404.html" and "/" not in rel
        new = block(title, desc, page_url(rel), noindex)

        # Strip any previous block, then any stray hand-written social tags, then
        # insert fresh. Doing it in that order keeps the script idempotent and
        # cannot leave duplicates behind.
        s = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", "", s, flags=re.S)
        s = re.sub(r'[ \t]*<meta (?:property="og:[^"]*"|name="twitter:[^"]*")[^>]*>\n?', "", s)
        s = re.sub(r'[ \t]*<link rel="canonical"[^>]*>\n?', "", s)

        # Insert just before the stylesheet so the tags sit with the rest of <head>.
        idx = s.find('<link rel="stylesheet"')
        if idx == -1:
            idx = s.find("</head>")
        if idx == -1:
            print(f"  !! no <head> in {rel}, skipped")
            continue
        s = s[:idx] + new + "\n" + s[idx:]

        path.write_text(s, encoding="utf-8")

    print(f"stamped {len(pages)} pages")
    print(f"  canonical root : {SITE_URL}")
    print(f"  og:image       : {SITE_URL + CARD}")


if __name__ == "__main__":
    main()
